import type { ReadySceneSpec } from "@/content/scenes/factory";
import {
  localeFromSpec,
  scenarioFromSpec,
} from "@/content/scenes/factory";

const SPECS: ReadySceneSpec[] = [
  {
    id: "find_apartment",
    worldId: "germany",
    categoryId: "housing",
    locationId: "apartment",
    title: "Searching for an apartment",
    summary: "Call about a listing and ask if you can visit.",
    estimatedMinutes: 8,
    concepts: ["questions", "vocabulary_housing", "polite_requests"],
    character: { id: "herr_lang", name: "Herr Lang", role: "Landlord" },
    openingLine: "Guten Tag, hier ist Herr Lang. Sie rufen wegen der Wohnung an?",
    context: "You found a listing and are calling the landlord.",
    goal: "Ask about rooms, rent, and whether you can visit.",
    objectives: [
      { id: "greet", label: "Greet the landlord" },
      { id: "ask_rooms", label: "Ask about the rooms" },
      { id: "ask_rent", label: "Ask about the rent" },
      { id: "ask_visit", label: "Ask to visit" },
      { id: "close", label: "Close politely" },
    ],
    vocabulary: [
      { term: "Wohnung", meaningEn: "apartment" },
      { term: "Miete", meaningEn: "rent" },
      { term: "Besichtigung", meaningEn: "viewing" },
    ],
  },
  {
    id: "contact_landlord",
    worldId: "germany",
    categoryId: "housing",
    locationId: "apartment",
    title: "Contacting a landlord",
    summary: "Write or speak to a landlord about a problem or a visit.",
    estimatedMinutes: 8,
    concepts: ["polite_requests", "vocabulary_housing", "formal_language"],
    character: { id: "frau_stein", name: "Frau Stein", role: "Landlord" },
    openingLine: "Guten Tag. Sie haben wegen der Wohnung geschrieben?",
    context: "You need to speak with the landlord about the apartment.",
    goal: "Explain why you are contacting them and agree on a next step.",
    objectives: [
      { id: "greet", label: "Greet the landlord" },
      { id: "explain", label: "Explain why you are contacting them" },
      { id: "ask_next", label: "Ask what happens next" },
      { id: "close", label: "Close politely" },
    ],
    vocabulary: [
      { term: "Vermieterin", meaningEn: "landlady" },
      { term: "Nachricht", meaningEn: "message" },
    ],
  },
  {
    id: "move_in",
    worldId: "germany",
    categoryId: "housing",
    locationId: "apartment",
    title: "Moving in",
    summary: "Collect the keys and check the apartment on moving day.",
    estimatedMinutes: 8,
    concepts: ["vocabulary_housing", "questions", "polite_requests"],
    character: { id: "herr_vogel", name: "Herr Vogel", role: "Building manager" },
    openingLine: "Willkommen. Heute übergeben wir die Schlüssel.",
    context: "It is moving day. You meet at the apartment for the keys.",
    goal: "Collect the keys, ask about the mailbox, and confirm the handover.",
    objectives: [
      { id: "greet", label: "Greet the manager" },
      { id: "keys", label: "Ask for the keys" },
      { id: "mailbox", label: "Ask about the mailbox" },
      { id: "close", label: "Thank them and close" },
    ],
    vocabulary: [
      { term: "Schlüssel", meaningEn: "keys" },
      { term: "Briefkasten", meaningEn: "mailbox" },
      { term: "Übergabe", meaningEn: "handover" },
    ],
  },
  {
    id: "bring_documents",
    worldId: "germany",
    categoryId: "city_registration",
    locationId: "buergeramt",
    title: "Bringing your documents",
    summary: "Check which papers you need at the Bürgeramt.",
    estimatedMinutes: 8,
    disclaimer: "not_legal_advice",
    concepts: ["documents", "vocabulary_administration", "questions"],
    character: { id: "frau_holz", name: "Frau Holz", role: "Bürgeramt clerk" },
    openingLine: "Guten Tag. Welche Unterlagen haben Sie dabei?",
    context: "You are at the Bürgeramt counter with your papers.",
    goal: "Show your documents and ask if anything is missing.",
    objectives: [
      { id: "greet", label: "Greet the clerk" },
      { id: "show_papers", label: "Say which documents you have" },
      { id: "ask_missing", label: "Ask if anything is missing" },
      { id: "close", label: "Close politely" },
    ],
    vocabulary: [
      { term: "Unterlagen", meaningEn: "documents" },
      { term: "Pass", meaningEn: "passport" },
      { term: "fehlen", meaningEn: "to be missing" },
    ],
  },
  {
    id: "waiting_number",
    worldId: "germany",
    categoryId: "city_registration",
    locationId: "buergeramt",
    title: "Waiting with a number",
    summary: "Take a number and ask when you will be called.",
    estimatedMinutes: 7,
    disclaimer: "not_legal_advice",
    concepts: ["questions", "vocabulary_administration", "formal_language"],
    character: { id: "herr_baum", name: "Herr Baum", role: "Reception clerk" },
    openingLine: "Guten Tag. Ziehen Sie bitte eine Nummer.",
    context: "The Bürgeramt waiting area is busy.",
    goal: "Take a number and ask how long the wait might be.",
    objectives: [
      { id: "greet", label: "Greet reception" },
      { id: "number", label: "Ask about the waiting number" },
      { id: "wait", label: "Ask how long it might take" },
      { id: "close", label: "Thank them" },
    ],
    vocabulary: [
      { term: "Nummer", meaningEn: "number" },
      { term: "warten", meaningEn: "to wait" },
      { term: "Schalter", meaningEn: "counter" },
    ],
  },
  {
    id: "pickup_certificate",
    worldId: "germany",
    categoryId: "city_registration",
    locationId: "buergeramt",
    title: "Collecting a certificate",
    summary: "Pick up your Anmeldung confirmation at the counter.",
    estimatedMinutes: 7,
    disclaimer: "not_legal_advice",
    concepts: ["documents", "vocabulary_administration", "formal_language"],
    character: { id: "frau_klein", name: "Frau Klein", role: "Bürgeramt clerk" },
    openingLine: "Ihre Anmeldung ist fertig. Ich gebe Ihnen die Bescheinigung.",
    context: "You return to collect a registration certificate.",
    goal: "Confirm your name, collect the paper, and ask if you need a copy.",
    objectives: [
      { id: "greet", label: "Greet the clerk" },
      { id: "name", label: "Confirm your name" },
      { id: "collect", label: "Collect the certificate" },
      { id: "close", label: "Thank them" },
    ],
    vocabulary: [
      { term: "Bescheinigung", meaningEn: "certificate" },
      { term: "Anmeldung", meaningEn: "registration" },
      { term: "Kopie", meaningEn: "copy" },
    ],
  },
  {
    id: "apply_residence_permit",
    worldId: "germany",
    categoryId: "residence",
    locationId: "auslaenderbehoerde",
    title: "Applying for a residence permit",
    summary: "Start a language simulation of a permit application visit.",
    estimatedMinutes: 10,
    disclaimer: "not_legal_advice",
    concepts: ["formal_language", "documents", "vocabulary_administration"],
    character: { id: "herr_nacht", name: "Herr Nacht", role: "Immigration clerk" },
    openingLine: "Guten Tag. Sie möchten einen Aufenthaltstitel beantragen?",
    context: "You have an appointment to talk about a residence permit.",
    goal: "Explain why you are here and ask which documents they need.",
    objectives: [
      { id: "greet", label: "Greet the clerk" },
      { id: "reason", label: "Explain why you are here" },
      { id: "documents", label: "Ask which documents are needed" },
      { id: "close", label: "Ask about next steps" },
    ],
    vocabulary: [
      { term: "beantragen", meaningEn: "to apply" },
      { term: "Aufenthaltstitel", meaningEn: "residence permit" },
    ],
  },
  {
    id: "extend_residence_permit",
    worldId: "germany",
    categoryId: "residence",
    locationId: "auslaenderbehoerde",
    title: "Extending a residence permit",
    summary: "Ask how to extend a permit that will expire soon.",
    estimatedMinutes: 10,
    disclaimer: "not_legal_advice",
    concepts: ["formal_language", "questions", "vocabulary_administration"],
    character: { id: "frau_west", name: "Frau West", role: "Immigration clerk" },
    openingLine: "Guten Tag. Ihr Aufenthaltstitel läuft bald ab?",
    context: "Your permit will expire and you need to talk about an extension.",
    goal: "Say when it expires and ask what you should do next.",
    objectives: [
      { id: "greet", label: "Greet the clerk" },
      { id: "expiry", label: "Say when the permit expires" },
      { id: "extend", label: "Ask about an extension" },
      { id: "close", label: "Confirm the next step" },
    ],
    vocabulary: [
      { term: "verlängern", meaningEn: "to extend" },
      { term: "ablaufen", meaningEn: "to expire" },
    ],
  },
  {
    id: "permit_status",
    worldId: "germany",
    categoryId: "residence",
    locationId: "auslaenderbehoerde",
    title: "Asking about application status",
    summary: "Ask whether your application is still being processed.",
    estimatedMinutes: 8,
    disclaimer: "not_legal_advice",
    concepts: ["questions", "formal_language", "vocabulary_administration"],
    character: { id: "herr_tal", name: "Herr Tal", role: "Immigration clerk" },
    openingLine: "Guten Tag. Sie fragen nach dem Stand Ihres Antrags?",
    context: "You already applied and want a simple status update.",
    goal: "Give your name and ask if there is any news.",
    objectives: [
      { id: "greet", label: "Greet the clerk" },
      { id: "name", label: "Give your name" },
      { id: "status", label: "Ask about the status" },
      { id: "close", label: "Thank them" },
    ],
    vocabulary: [
      { term: "Antrag", meaningEn: "application" },
      { term: "Stand", meaningEn: "status" },
    ],
  },
  {
    id: "university_enrollment",
    worldId: "germany",
    categoryId: "university",
    locationId: "university",
    title: "University enrollment",
    summary: "Enroll and ask what you still need to submit.",
    estimatedMinutes: 9,
    concepts: ["questions", "documents", "formal_language"],
    character: { id: "frau_beckmann", name: "Frau Beckmann", role: "Enrollment officer" },
    openingLine: "Guten Tag. Sie möchten sich immatrikulieren?",
    context: "You are at the student office to enroll.",
    goal: "Confirm your course and ask which papers they still need.",
    objectives: [
      { id: "greet", label: "Greet the officer" },
      { id: "course", label: "Name your course" },
      { id: "papers", label: "Ask which papers are needed" },
      { id: "close", label: "Thank them" },
    ],
    vocabulary: [
      { term: "immatrikulieren", meaningEn: "to enroll" },
      { term: "Studiengang", meaningEn: "degree program" },
    ],
  },
  {
    id: "international_office",
    worldId: "germany",
    categoryId: "university",
    locationId: "university",
    title: "International office",
    summary: "Ask an advisor about courses, housing, or a campus card.",
    estimatedMinutes: 8,
    concepts: ["questions", "polite_requests", "formal_language"],
    character: { id: "herr_lima", name: "Herr Lima", role: "International advisor" },
    openingLine: "Hello — ah, Guten Tag. Wie kann das International Office helfen?",
    context: "You visit the international office on campus.",
    goal: "Explain what you need and ask one clear question.",
    objectives: [
      { id: "greet", label: "Greet the advisor" },
      { id: "need", label: "Explain what you need" },
      { id: "ask", label: "Ask a follow-up question" },
      { id: "close", label: "Thank them" },
    ],
    vocabulary: [
      { term: "International Office", meaningEn: "international office" },
      { term: "Campus", meaningEn: "campus" },
    ],
  },
  {
    id: "talk_to_professor",
    worldId: "germany",
    categoryId: "university",
    locationId: "university",
    title: "Talking to a professor",
    summary: "Ask about office hours, an assignment, or an exam.",
    estimatedMinutes: 8,
    concepts: ["questions", "formal_language", "polite_requests"],
    character: { id: "prof_keller", name: "Prof. Keller", role: "Professor" },
    openingLine: "Guten Tag. Sie wollten mich kurz sprechen?",
    context: "You catch your professor after class.",
    goal: "Ask one academic question politely and confirm the answer.",
    objectives: [
      { id: "greet", label: "Greet the professor" },
      { id: "ask", label: "Ask your question" },
      { id: "confirm", label: "Confirm the answer" },
      { id: "close", label: "Thank them" },
    ],
    vocabulary: [
      { term: "Sprechstunde", meaningEn: "office hours" },
      { term: "Prüfung", meaningEn: "exam" },
    ],
  },
  {
    id: "exam_registration",
    worldId: "germany",
    categoryId: "university",
    locationId: "university",
    title: "Registering for an exam",
    summary: "Register for an exam and confirm the date.",
    estimatedMinutes: 7,
    concepts: ["questions", "documents", "vocabulary_administration"],
    character: { id: "frau_ort", name: "Frau Ort", role: "Exam office clerk" },
    openingLine: "Guten Tag. Sie möchten sich für eine Prüfung anmelden?",
    context: "You are at the exam office.",
    goal: "Name the exam and confirm the date and deadline.",
    objectives: [
      { id: "greet", label: "Greet the clerk" },
      { id: "exam", label: "Name the exam" },
      { id: "date", label: "Ask about the date" },
      { id: "close", label: "Confirm you are registered" },
    ],
    vocabulary: [
      { term: "anmelden", meaningEn: "to register" },
      { term: "Frist", meaningEn: "deadline" },
    ],
  },
  {
    id: "job_interview",
    worldId: "germany",
    categoryId: "work",
    locationId: "workplace",
    title: "Job interview",
    summary: "Introduce yourself and answer simple interview questions.",
    estimatedMinutes: 10,
    concepts: ["formal_language", "questions", "polite_requests"],
    character: { id: "frau_brand", name: "Frau Brand", role: "Hiring manager" },
    openingLine: "Guten Tag. Schön, dass Sie da sind. Erzählen Sie kurz von sich.",
    context: "You sit down for a first job interview.",
    goal: "Introduce yourself, answer why you applied, and ask one question.",
    objectives: [
      { id: "greet", label: "Greet the interviewer" },
      { id: "intro", label: "Introduce yourself" },
      { id: "why", label: "Say why you applied" },
      { id: "ask", label: "Ask a question about the job" },
    ],
    vocabulary: [
      { term: "Bewerbung", meaningEn: "application" },
      { term: "Erfahrung", meaningEn: "experience" },
    ],
  },
  {
    id: "first_day_at_work",
    worldId: "germany",
    categoryId: "work",
    locationId: "workplace",
    title: "First day at work",
    summary: "Meet a colleague and ask where things are.",
    estimatedMinutes: 8,
    concepts: ["questions", "polite_requests"],
    character: { id: "max_weber", name: "Max Weber", role: "Colleague" },
    openingLine: "Hallo! Du bist neu, oder? Ich zeige dir kurz alles.",
    context: "It is your first morning at a new workplace.",
    goal: "Introduce yourself and ask about the kitchen, desk, and hours.",
    objectives: [
      { id: "greet", label: "Greet your colleague" },
      { id: "intro", label: "Introduce yourself" },
      { id: "ask_place", label: "Ask where something is" },
      { id: "hours", label: "Ask about working hours" },
    ],
    vocabulary: [
      { term: "Arbeitsplatz", meaningEn: "workplace" },
      { term: "Arbeitszeit", meaningEn: "working hours" },
    ],
  },
  {
    id: "request_urlaub",
    worldId: "germany",
    categoryId: "work",
    locationId: "workplace",
    title: "Asking for time off",
    summary: "Ask your manager for Urlaub on specific days.",
    estimatedMinutes: 7,
    concepts: ["polite_requests", "formal_language", "questions"],
    character: { id: "herr_graf", name: "Herr Graf", role: "Manager" },
    openingLine: "Guten Tag. Sie wollten wegen Urlaub sprechen?",
    context: "You knock on your manager's door about vacation days.",
    goal: "Ask for specific days off and confirm whether it is possible.",
    objectives: [
      { id: "greet", label: "Greet your manager" },
      { id: "ask", label: "Ask for time off" },
      { id: "dates", label: "Give the dates" },
      { id: "confirm", label: "Confirm the answer" },
    ],
    vocabulary: [
      { term: "Urlaub", meaningEn: "vacation / time off" },
      { term: "Tage", meaningEn: "days" },
    ],
  },
  {
    id: "talk_to_hr",
    worldId: "germany",
    categoryId: "work",
    locationId: "workplace",
    title: "Talking to HR",
    summary: "Ask HR about a contract detail, a form, or a certificate.",
    estimatedMinutes: 8,
    concepts: ["formal_language", "documents", "questions"],
    character: { id: "frau_reiter", name: "Frau Reiter", role: "HR officer" },
    openingLine: "Guten Tag. Personalabteilung — wie kann ich helfen?",
    context: "You have a short appointment with HR.",
    goal: "Explain what you need and ask when it will be ready.",
    objectives: [
      { id: "greet", label: "Greet HR" },
      { id: "need", label: "Explain what you need" },
      { id: "when", label: "Ask when it will be ready" },
      { id: "close", label: "Thank them" },
    ],
    vocabulary: [
      { term: "Personalabteilung", meaningEn: "HR" },
      { term: "Vertrag", meaningEn: "contract" },
    ],
  },
  {
    id: "doctor_appointment",
    worldId: "germany",
    categoryId: "healthcare",
    locationId: "doctors_office",
    title: "Making a doctor's appointment",
    summary: "Call or speak at reception to book a visit.",
    estimatedMinutes: 7,
    disclaimer: "not_medical_advice",
    concepts: ["questions", "polite_requests", "vocabulary_health"],
    character: { id: "frau_sander", name: "Frau Sander", role: "Receptionist" },
    openingLine: "Arztpraxis, guten Tag. Sie möchten einen Termin?",
    context: "You need to book a doctor's appointment.",
    goal: "Say why you need a visit and agree on a day.",
    objectives: [
      { id: "greet", label: "Greet reception" },
      { id: "reason", label: "Say why you need an appointment" },
      { id: "day", label: "Agree on a day" },
      { id: "close", label: "Confirm the time" },
    ],
    vocabulary: [
      { term: "Termin", meaningEn: "appointment" },
      { term: "Arztpraxis", meaningEn: "doctor's office" },
    ],
  },
  {
    id: "doctor_reception",
    worldId: "germany",
    categoryId: "healthcare",
    locationId: "doctors_office",
    title: "At the doctor's reception",
    summary: "Check in and hand over your insurance card.",
    estimatedMinutes: 7,
    disclaimer: "not_medical_advice",
    concepts: ["documents", "vocabulary_health", "formal_language"],
    character: { id: "herr_pfeiffer", name: "Herr Pfeiffer", role: "Receptionist" },
    openingLine: "Guten Tag. Haben Sie Ihre Versichertenkarte dabei?",
    context: "You arrive for your appointment and check in.",
    goal: "Give your name, hand over your card, and take a seat.",
    objectives: [
      { id: "greet", label: "Greet reception" },
      { id: "name", label: "Give your name" },
      { id: "card", label: "Hand over your insurance card" },
      { id: "sit", label: "Ask where to wait" },
    ],
    vocabulary: [
      { term: "Versichertenkarte", meaningEn: "insurance card" },
      { term: "Wartezimmer", meaningEn: "waiting room" },
    ],
  },
  {
    id: "explain_symptoms",
    worldId: "germany",
    categoryId: "healthcare",
    locationId: "doctors_office",
    title: "Explaining symptoms",
    summary: "Tell the doctor what hurts and since when.",
    estimatedMinutes: 8,
    disclaimer: "not_medical_advice",
    concepts: ["vocabulary_health", "questions", "polite_requests"],
    character: { id: "dr_mann", name: "Dr. Mann", role: "Doctor" },
    openingLine: "Guten Tag. Was führt Sie heute zu mir?",
    context: "You sit down with the doctor.",
    goal: "Describe the problem simply and ask what to do next.",
    objectives: [
      { id: "greet", label: "Greet the doctor" },
      { id: "symptom", label: "Describe the symptom" },
      { id: "since", label: "Say since when" },
      { id: "ask", label: "Ask what to do next" },
    ],
    vocabulary: [
      { term: "Schmerzen", meaningEn: "pain" },
      { term: "Fieber", meaningEn: "fever" },
    ],
  },
  {
    id: "pharmacy",
    worldId: "germany",
    categoryId: "healthcare",
    locationId: "pharmacy",
    title: "At the pharmacy",
    summary: "Ask for medicine and how to take it.",
    estimatedMinutes: 7,
    disclaimer: "not_medical_advice",
    concepts: ["vocabulary_health", "questions", "polite_requests"],
    character: { id: "frau_apfel", name: "Frau Apfel", role: "Pharmacist" },
    openingLine: "Guten Tag, wie kann ich Ihnen helfen?",
    context: "You are at an Apotheke counter.",
    goal: "Ask for something for a cold or headache and how to take it.",
    objectives: [
      { id: "greet", label: "Greet the pharmacist" },
      { id: "need", label: "Say what you need" },
      { id: "how", label: "Ask how to take it" },
      { id: "pay", label: "Ask about the price" },
    ],
    vocabulary: [
      { term: "Apotheke", meaningEn: "pharmacy" },
      { term: "Medikament", meaningEn: "medicine" },
    ],
  },
  {
    id: "buy_train_ticket",
    worldId: "germany",
    categoryId: "transport",
    locationId: "train_station",
    title: "Buying a train ticket",
    summary: "Buy a ticket to another city at the counter.",
    estimatedMinutes: 8,
    concepts: ["questions", "polite_requests", "vocabulary_travel"],
    character: { id: "herr_gleis", name: "Herr Gleis", role: "Ticket clerk" },
    openingLine: "Guten Tag. Wohin möchten Sie fahren?",
    context: "You are at the station ticket counter.",
    goal: "Name your destination, ask the next train, and buy a ticket.",
    objectives: [
      { id: "greet", label: "Greet the clerk" },
      { id: "city", label: "Name your destination" },
      { id: "next", label: "Ask about the next train" },
      { id: "buy", label: "Buy the ticket" },
    ],
    vocabulary: [
      { term: "Fahrkarte", meaningEn: "ticket" },
      { term: "Gleis", meaningEn: "platform" },
    ],
  },
  {
    id: "delayed_train",
    worldId: "germany",
    categoryId: "transport",
    locationId: "train_station",
    title: "A delayed train",
    summary: "Ask why the train is late and what to do.",
    estimatedMinutes: 7,
    concepts: ["questions", "vocabulary_travel", "polite_requests"],
    character: { id: "frau_bahn", name: "Frau Bahn", role: "Station staff" },
    openingLine: "Der Zug hat Verspätung. Kann ich Ihnen helfen?",
    context: "The display shows a delay.",
    goal: "Ask how late it is and whether you need another train.",
    objectives: [
      { id: "greet", label: "Greet station staff" },
      { id: "delay", label: "Ask about the delay" },
      { id: "option", label: "Ask about another train" },
      { id: "close", label: "Thank them" },
    ],
    vocabulary: [
      { term: "Verspätung", meaningEn: "delay" },
      { term: "Zug", meaningEn: "train" },
    ],
  },
  {
    id: "ask_directions",
    worldId: "germany",
    categoryId: "transport",
    locationId: "train_station",
    title: "Asking for directions",
    summary: "Find a platform, exit, or the S-Bahn.",
    estimatedMinutes: 6,
    concepts: ["questions", "vocabulary_travel"],
    character: { id: "lena_ort", name: "Lena", role: "Station helper" },
    openingLine: "Hallo, Sie suchen etwas?",
    context: "You are lost in a big station.",
    goal: "Ask for a platform or exit and repeat the directions.",
    objectives: [
      { id: "greet", label: "Greet the helper" },
      { id: "ask", label: "Ask for directions" },
      { id: "repeat", label: "Repeat the directions" },
      { id: "thanks", label: "Thank them" },
    ],
    vocabulary: [
      { term: "Ausgang", meaningEn: "exit" },
      { term: "links", meaningEn: "left" },
      { term: "rechts", meaningEn: "right" },
    ],
  },
  {
    id: "lost_property",
    worldId: "germany",
    categoryId: "transport",
    locationId: "train_station",
    title: "Lost property",
    summary: "Report a lost bag or phone at the station.",
    estimatedMinutes: 8,
    concepts: ["questions", "polite_requests", "vocabulary_travel"],
    character: { id: "herr_fund", name: "Herr Fund", role: "Lost-and-found clerk" },
    openingLine: "Fundbüro, guten Tag. Was haben Sie verloren?",
    context: "You go to lost and found after missing an item.",
    goal: "Describe the item and where you last had it.",
    objectives: [
      { id: "greet", label: "Greet the clerk" },
      { id: "item", label: "Describe the lost item" },
      { id: "where", label: "Say where you last had it" },
      { id: "close", label: "Ask what happens next" },
    ],
    vocabulary: [
      { term: "verloren", meaningEn: "lost" },
      { term: "Fundbüro", meaningEn: "lost and found" },
    ],
  },
  {
    id: "supermarket",
    worldId: "germany",
    categoryId: "everyday",
    locationId: "supermarket",
    title: "At the supermarket",
    summary: "Ask where something is and pay at the checkout.",
    estimatedMinutes: 7,
    concepts: ["questions", "polite_requests"],
    character: { id: "tim_markt", name: "Tim", role: "Shop assistant" },
    openingLine: "Hallo, kann ich Ihnen helfen?",
    context: "You cannot find an item in a German supermarket.",
    goal: "Ask for an aisle and then pay.",
    objectives: [
      { id: "greet", label: "Greet the assistant" },
      { id: "find", label: "Ask where an item is" },
      { id: "pay", label: "Ask if you can pay by card" },
      { id: "thanks", label: "Thank them" },
    ],
    vocabulary: [
      { term: "Kasse", meaningEn: "checkout" },
      { term: "Regal", meaningEn: "shelf" },
    ],
  },
  {
    id: "cafe",
    worldId: "germany",
    categoryId: "everyday",
    locationId: "restaurant",
    title: "At a café",
    summary: "Order coffee and a cake, then ask for the bill.",
    estimatedMinutes: 7,
    concepts: ["polite_requests", "questions"],
    character: { id: "nina_cafe", name: "Nina", role: "Barista" },
    openingLine: "Hallo! Was darf es sein?",
    context: "You sit down in a neighborhood café.",
    goal: "Order a drink and something to eat, then pay.",
    objectives: [
      { id: "greet", label: "Greet the barista" },
      { id: "drink", label: "Order a drink" },
      { id: "food", label: "Order something to eat" },
      { id: "bill", label: "Ask for the bill" },
    ],
    vocabulary: [
      { term: "Kaffee", meaningEn: "coffee" },
      { term: "Stück Kuchen", meaningEn: "a piece of cake" },
    ],
  },
  {
    id: "bakery",
    worldId: "germany",
    categoryId: "everyday",
    locationId: "supermarket",
    title: "At the bakery",
    summary: "Order bread and rolls in the morning rush.",
    estimatedMinutes: 6,
    concepts: ["polite_requests", "questions"],
    character: { id: "ulla_back", name: "Ulla", role: "Baker" },
    openingLine: "Guten Morgen! Was darf ich Ihnen geben?",
    context: "You are at a German bakery counter.",
    goal: "Order bread or rolls and ask the price.",
    objectives: [
      { id: "greet", label: "Greet the baker" },
      { id: "order", label: "Order bread or rolls" },
      { id: "price", label: "Ask the price" },
      { id: "thanks", label: "Thank them" },
    ],
    vocabulary: [
      { term: "Brötchen", meaningEn: "roll" },
      { term: "Brot", meaningEn: "bread" },
    ],
  },
];

export const germanyReadyScenarios = SPECS.map((spec) =>
  scenarioFromSpec(spec, "de"),
);

export const germanyReadyLocaleContent = SPECS.map((spec) =>
  localeFromSpec(spec, "de"),
);
