import type { ReadySceneSpec } from "@/content/scenes/factory";
import {
  localeFromSpec,
  scenarioFromSpec,
} from "@/content/scenes/factory";

const SPECS: ReadySceneSpec[] = [
  {
    id: "find_apartment",
    worldId: "france",
    categoryId: "housing",
    locationId: "apartment",
    title: "Searching for an apartment",
    summary: "Call about a listing and ask if you can visit.",
    estimatedMinutes: 8,
    concepts: ["questions", "gender", "vocabulary_housing"],
    character: { id: "m_durand", name: "Monsieur Durand", role: "Landlord" },
    openingLine: "Allô, bonjour. Vous appelez pour l'appartement ?",
    context: "You found a listing and are calling the landlord.",
    goal: "Ask about rooms, rent, and whether you can visit.",
    objectives: [
      { id: "greet", label: "Greet the landlord" },
      { id: "ask_rooms", label: "Ask about the rooms" },
      { id: "ask_rent", label: "Ask about the rent" },
      { id: "ask_visit", label: "Ask to visit" },
      { id: "close", label: "Close politely" },
    ],
    vocabulary: [
      { term: "appartement", meaningEn: "apartment" },
      { term: "loyer", meaningEn: "rent" },
      { term: "visite", meaningEn: "viewing" },
    ],
  },
  {
    id: "contact_landlord",
    worldId: "france",
    categoryId: "housing",
    locationId: "apartment",
    title: "Contacting a landlord",
    summary: "Speak with the landlord about a visit or a problem.",
    estimatedMinutes: 8,
    concepts: ["polite_requests", "vocabulary_housing", "formal_language"],
    character: { id: "mme_petit", name: "Madame Petit", role: "Landlady" },
    openingLine: "Bonjour. Vous m'avez écrit pour l'appartement ?",
    context: "You need to speak with the landlady.",
    goal: "Explain why you are contacting them and agree on a next step.",
    objectives: [
      { id: "greet", label: "Greet the landlady" },
      { id: "explain", label: "Explain why you are contacting them" },
      { id: "ask_next", label: "Ask what happens next" },
      { id: "close", label: "Close politely" },
    ],
    vocabulary: [
      { term: "propriétaire", meaningEn: "landlord / landlady" },
      { term: "message", meaningEn: "message" },
    ],
  },
  {
    id: "move_in",
    worldId: "france",
    categoryId: "housing",
    locationId: "apartment",
    title: "Moving in",
    summary: "Collect the keys and check the apartment on moving day.",
    estimatedMinutes: 8,
    concepts: ["vocabulary_housing", "questions", "polite_requests"],
    character: { id: "m_noel", name: "Monsieur Noël", role: "Building manager" },
    openingLine: "Bienvenue. Aujourd'hui, on vous donne les clés.",
    context: "It is moving day. You meet for the keys.",
    goal: "Collect the keys, ask about the mailbox, and confirm the handover.",
    objectives: [
      { id: "greet", label: "Greet the manager" },
      { id: "keys", label: "Ask for the keys" },
      { id: "mailbox", label: "Ask about the mailbox" },
      { id: "close", label: "Thank them and close" },
    ],
    vocabulary: [
      { term: "clés", meaningEn: "keys" },
      { term: "boîte aux lettres", meaningEn: "mailbox" },
    ],
  },
  {
    id: "bring_documents",
    worldId: "france",
    categoryId: "city_registration",
    locationId: "mairie",
    title: "Bringing your documents",
    summary: "Check which papers you need at the mairie.",
    estimatedMinutes: 8,
    disclaimer: "not_legal_advice",
    concepts: ["documents", "vocabulary_administration", "questions"],
    character: { id: "mme_blanc", name: "Madame Blanc", role: "Mairie clerk" },
    openingLine: "Bonjour. Vous avez vos papiers ?",
    context: "You are at the mairie counter with your papers.",
    goal: "Show your documents and ask if anything is missing.",
    objectives: [
      { id: "greet", label: "Greet the clerk" },
      { id: "show_papers", label: "Say which documents you have" },
      { id: "ask_missing", label: "Ask if anything is missing" },
      { id: "close", label: "Close politely" },
    ],
    vocabulary: [
      { term: "papiers", meaningEn: "papers / documents" },
      { term: "passeport", meaningEn: "passport" },
    ],
  },
  {
    id: "waiting_number",
    worldId: "france",
    categoryId: "city_registration",
    locationId: "mairie",
    title: "Waiting with a number",
    summary: "Take a ticket and ask when you will be called.",
    estimatedMinutes: 7,
    disclaimer: "not_legal_advice",
    concepts: ["questions", "vocabulary_administration", "formal_language"],
    character: { id: "m_robin", name: "Monsieur Robin", role: "Reception clerk" },
    openingLine: "Bonjour. Prenez un ticket, s'il vous plaît.",
    context: "The mairie waiting area is busy.",
    goal: "Take a number and ask how long the wait might be.",
    objectives: [
      { id: "greet", label: "Greet reception" },
      { id: "number", label: "Ask about the waiting number" },
      { id: "wait", label: "Ask how long it might take" },
      { id: "close", label: "Thank them" },
    ],
    vocabulary: [
      { term: "ticket", meaningEn: "ticket / number" },
      { term: "attendre", meaningEn: "to wait" },
    ],
  },
  {
    id: "pickup_certificate",
    worldId: "france",
    categoryId: "city_registration",
    locationId: "mairie",
    title: "Collecting a certificate",
    summary: "Pick up a document at the mairie counter.",
    estimatedMinutes: 7,
    disclaimer: "not_legal_advice",
    concepts: ["documents", "vocabulary_administration", "formal_language"],
    character: { id: "mme_faure", name: "Madame Faure", role: "Mairie clerk" },
    openingLine: "Votre document est prêt. Je vous le donne.",
    context: "You return to collect a certificate.",
    goal: "Confirm your name, collect the paper, and ask if you need a copy.",
    objectives: [
      { id: "greet", label: "Greet the clerk" },
      { id: "name", label: "Confirm your name" },
      { id: "collect", label: "Collect the certificate" },
      { id: "close", label: "Thank them" },
    ],
    vocabulary: [
      { term: "attestation", meaningEn: "certificate" },
      { term: "copie", meaningEn: "copy" },
    ],
  },
  {
    id: "supermarket",
    worldId: "france",
    categoryId: "everyday",
    locationId: "supermarket",
    title: "At the supermarket",
    summary: "Ask where something is and pay at the checkout.",
    estimatedMinutes: 7,
    concepts: ["questions", "polite_requests"],
    character: { id: "leo_marche", name: "Léo", role: "Shop assistant" },
    openingLine: "Bonjour, je peux vous aider ?",
    context: "You cannot find an item in a French supermarket.",
    goal: "Ask for an aisle and then pay.",
    objectives: [
      { id: "greet", label: "Greet the assistant" },
      { id: "find", label: "Ask where an item is" },
      { id: "pay", label: "Ask if you can pay by card" },
      { id: "thanks", label: "Thank them" },
    ],
    vocabulary: [
      { term: "caisse", meaningEn: "checkout" },
      { term: "rayon", meaningEn: "aisle" },
    ],
  },
  {
    id: "cafe",
    worldId: "france",
    categoryId: "everyday",
    locationId: "restaurant",
    title: "At a café",
    summary: "Order coffee and a pastry, then ask for the bill.",
    estimatedMinutes: 7,
    concepts: ["polite_requests", "questions"],
    character: { id: "chloe_cafe", name: "Chloé", role: "Server" },
    openingLine: "Bonjour ! Qu'est-ce que je vous sers ?",
    context: "You sit down in a neighborhood café.",
    goal: "Order a drink and something to eat, then pay.",
    objectives: [
      { id: "greet", label: "Greet the server" },
      { id: "drink", label: "Order a drink" },
      { id: "food", label: "Order something to eat" },
      { id: "bill", label: "Ask for the bill" },
    ],
    vocabulary: [
      { term: "café", meaningEn: "coffee" },
      { term: "croissant", meaningEn: "croissant" },
    ],
  },
  {
    id: "bakery",
    worldId: "france",
    categoryId: "everyday",
    locationId: "bakery",
    title: "At the bakery",
    summary: "Order bread and a pastry in the morning.",
    estimatedMinutes: 6,
    concepts: ["polite_requests", "questions"],
    character: { id: "mme_pain", name: "Madame Pain", role: "Baker" },
    openingLine: "Bonjour ! Qu'est-ce qui vous ferait plaisir ?",
    context: "You are at a boulangerie counter.",
    goal: "Order bread or a pastry and ask the price.",
    objectives: [
      { id: "greet", label: "Greet the baker" },
      { id: "order", label: "Order bread or a pastry" },
      { id: "price", label: "Ask the price" },
      { id: "thanks", label: "Thank them" },
    ],
    vocabulary: [
      { term: "baguette", meaningEn: "baguette" },
      { term: "pain", meaningEn: "bread" },
    ],
  },
];

export const franceReadyScenarios = SPECS.map((spec) =>
  scenarioFromSpec(spec, "fr"),
);

export const franceReadyLocaleContent = SPECS.map((spec) =>
  localeFromSpec(spec, "fr"),
);
